# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.72.0")

default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_SESSION"] = "---\n- !ruby/object:HTTP::Cookie\n  name: DES5efd5a028ec3a23a1f58984ff6755c7e1\n  value: HSARMTKNSRVTWFla8RRv5Pd/VVmpkVV3f0sh9sH2gkWhtQLyF3vIclcM0b0ZbW8OSLUoM/xJ4zlalHpGo1AChtAAjjvtC1nU5SyUJe06S4BOSPPn4rpQlIqKlCxUrBRI0bK76a03ezkmOKzjEBiRIb1ho0I=SRVT\n  domain: idmsa.apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 2592000\n  created_at: 2018-01-03 12:29:07.312316000 +08:00\n  accessed_at: 2018-01-04 18:46:03.469713000 +08:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJCQ2IxUXFYWDNmSkM4T3FKOTdtWUpRIn0.jaDf83ob-GQrSRheromoRGNxmiHGyup4yS-lERZkq5s\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2018-01-04 19:03:28.418596000 +08:00\n  accessed_at: *1\n"
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # cocoapods
  end

  desc "Runs Unit tests and UI tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sync_code_signing(type: "appstore") # more information: https://codesigning.guide
    # increment_build_number  # auto increment build number
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(scheme: "HeyUnitTest") # more options available
    upload_to_testflight
    # slack(message: "Successfully distributed a new beta build")

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Build a new .ipa"
  lane :build do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(scheme: "HeyUnitTest") # more options available
    # build_app(
    #   export_method: "app-store",
    #   export_options: {
    #     provisioningProfiles: { 
    #       "com.roy.HelloTestJenkins" => "HeyUnitTestProvisioningProfile"
    #     }
    #   }
    # )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    build_app(scheme: "HeyUnitTest") # more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
